import { randomUUID } from "node:crypto";
import { normalizeLabel } from "./identity.js";
import type { HybridKnowledgeRetrievalService, HybridRetrievalRequest } from "./hybridRetrieval.js";
import type { CanonicalKnowledgeRepository, GraphRepository, SpatialRepository, VectorRepository } from "./storage/contracts.js";
import type { KnowledgeNode, KnowledgeProposal } from "./types.js";

export type KnowledgeAgentMode = "navigator" | "curator";
export type KnowledgeAgentOutcome = "answered" | "proposed" | "insufficient" | "bounded" | "failed";
export interface KnowledgeAgentToolSchema { name: string; description: string; capability: "navigate" | "curate" | "inspect"; mutates: "none" | "proposals_only"; parameters: readonly string[]; }
export interface KnowledgeAgentToolResult { ok: boolean; data?: unknown; error?: string; canonicalIds?: string[]; strategies?: Record<string, unknown>; proposalIds?: string[]; }
export type KnowledgeAgentDecision = { kind: "tool"; tool: string; args: Record<string, unknown> } | { kind: "final"; answer: string; outcome?: KnowledgeAgentOutcome };
export interface KnowledgeAgentModelInput { runId: string; mode: KnowledgeAgentMode; goal: string; policy: string; tools: KnowledgeAgentToolSchema[]; steps: Array<{ tool: string; result: KnowledgeAgentToolResult }>; remainingToolCalls: number; remainingProposals: number; }
export interface KnowledgeAgentModelAdapter { next(input: KnowledgeAgentModelInput): Promise<KnowledgeAgentDecision>; }
export interface KnowledgeAgentAuditEvent { runId: string; mode: KnowledgeAgentMode; phase: "start" | "tool" | "finish"; tool?: string; ok?: boolean; canonicalIds?: string[]; proposalIds?: string[]; strategies?: Record<string, unknown>; degraded?: string[]; outcome?: KnowledgeAgentOutcome; counts?: Record<string, number>; }
export interface KnowledgeAgentAuditor { emit(event: KnowledgeAgentAuditEvent): void; }
export interface KnowledgeAgentLimits { maxToolCalls?: number; maxContextChars?: number; maxGraphHops?: number; maxResults?: number; maxProposals?: number; }
export interface KnowledgeAgentRunRequest { goal: string; mode?: KnowledgeAgentMode; limits?: KnowledgeAgentLimits; }
export interface KnowledgeAgentRunResult { runId: string; mode: KnowledgeAgentMode; answer: string; outcome: KnowledgeAgentOutcome; steps: Array<{ tool: string; args: Record<string, unknown>; result: KnowledgeAgentToolResult }>; proposalIds: string[]; canonicalIds: string[]; degradedDependencies: string[]; hitToolLimit: boolean; }
export interface KnowledgeAgentDependencies { canonical: CanonicalKnowledgeRepository; retrieval: HybridKnowledgeRetrievalService; graph?: GraphRepository; vector?: VectorRepository; spatial?: SpatialRepository; model: KnowledgeAgentModelAdapter; auditor?: KnowledgeAgentAuditor; }

interface ToolContext { runId: string; mode: KnowledgeAgentMode; limits: Required<KnowledgeAgentLimits>; proposalsUsed: number; }
interface AgentTool { schema: KnowledgeAgentToolSchema; execute(args: Record<string, unknown>, context: ToolContext): Promise<KnowledgeAgentToolResult>; }
const NAVIGATOR_POLICY = "Resolve explicit identity before broad semantics. Narrow by structured/graph scope when available. Inspect provenance before asserting knowledge. Retrieve iteratively within bounds, report degraded layers, and state insufficiency explicitly. Graph/vector candidates are never canonical truth.";
const CURATOR_POLICY = `${NAVIGATOR_POLICY} Distinguish identity, provenance, context, evidence, observation, relation and claim. Labels, semantic similarity and workspace never prove identity. Enrich a known identity when appropriate; preserve ambiguity and propose reconciliation when uncertain. Create pending proposals only; never approve, merge, supersede or arbitrate truth autonomously.`;
const n = (value: unknown, fallback: number, max: number) => Math.min(Math.max(Math.floor(typeof value === "number" ? value : fallback), 0), max);
const s = (value: unknown) => typeof value === "string" ? value.trim() : "";
const strings = (value: unknown): string[] => Array.isArray(value) ? [...new Set(value.filter((v): v is string => typeof v === "string" && !!v.trim()).map((v) => v.trim()))] : [];
const idsFrom = (value: unknown): string[] => { const out = new Set<string>(); const visit = (v: unknown) => { if (typeof v === "string" && /^[0-9a-f-]{36}$/i.test(v)) out.add(v); else if (Array.isArray(v)) v.forEach(visit); else if (v && typeof v === "object") Object.entries(v).forEach(([key, item]) => { if (/id$/i.test(key) || key === "nodes" || key === "items") visit(item); }); }; visit(value); return [...out]; };
const degradedFrom = (strategies: unknown): string[] => strategies && typeof strategies === "object" ? Object.entries(strategies).filter(([, value]) => value && typeof value === "object" && ["degraded", "unavailable"].includes(String((value as { state?: unknown }).state))).map(([key]) => key) : [];

const TOOL_PARAMETERS: Record<string, readonly string[]> = {
  "knowledge.resolve_entity": ["canonicalId?", "label?", "type?"],
  "knowledge.retrieve": ["canonicalIds?", "identityQueries?", "candidateCanonicalIds?", "graphRootIds?", "projectId?", "workspaceId?", "entityTypes?", "graphRelation?", "graphHops?", "queryVector?", "embeddingModel?", "embeddingModelVersion?", "includeEvidence?", "includeObservations?", "includeSources?", "overallLimit?", "contextBudget?"],
  "knowledge.semantic_search": ["queryVector", "embeddingModel", "embeddingModelVersion", "candidateCanonicalIds?", "workspaceId?", "entityTypes?", "limit?"],
  "knowledge.graph_expand": ["canonicalId", "hops?", "relation?", "workspaceId?"],
  "knowledge.find_path": ["fromId", "toId", "maxHops?", "workspaceId?"],
  "knowledge.get_node": ["canonicalId"], "knowledge.get_claims": ["rootIds", "graphHops?", "workspaceId?", "overallLimit?"],
  "knowledge.get_evidence": ["canonicalId", "limit?"], "knowledge.get_observations": ["canonicalId", "limit?"], "knowledge.get_sources": ["canonicalId"],
  "knowledge.spatial_search": ["longitude", "latitude", "distanceMeters", "workspaceId?"],
  "knowledge.propose_entity": ["type", "label", "description?", "workspaceId?", "canonicalId?"], "knowledge.propose_claim": ["label", "description?", "workspaceId?", "canonicalId?"],
  "knowledge.propose_relation": ["fromId", "relation", "toId", "confidence?"], "knowledge.propose_evidence": ["targetId", "sourceId", "stance", "excerpt?", "confidence?"],
  "knowledge.propose_observation": ["targetId", "sourceId?", "kind", "metadata?"], "knowledge.propose_merge": ["fromId", "intoId", "rationale?"],
  "knowledge.propose_supersede": ["oldClaimId", "newClaimId", "markOldDisputed?", "rationale?"], "knowledge.inspect_duplicates": ["label", "type?"],
  "knowledge.inspect_conflicts": ["canonicalId?"], "knowledge.inspect_structure": ["canonicalIds"],
};
function tool(name: string, description: string, capability: KnowledgeAgentToolSchema["capability"], mutates: KnowledgeAgentToolSchema["mutates"], execute: AgentTool["execute"]): AgentTool { return { schema: { name, description, capability, mutates, parameters: TOOL_PARAMETERS[name] ?? [] }, execute }; }
function request(args: Record<string, unknown>, limits: Required<KnowledgeAgentLimits>): HybridRetrievalRequest {
  return { canonicalIds: strings(args.canonicalIds), identityQueries: Array.isArray(args.identityQueries) ? args.identityQueries as HybridRetrievalRequest["identityQueries"] : undefined, candidateCanonicalIds: strings(args.candidateCanonicalIds), graphRootIds: strings(args.graphRootIds), projectId: s(args.projectId) || undefined, workspaceId: args.workspaceId === null ? null : s(args.workspaceId) || undefined, entityTypes: strings(args.entityTypes), graphRelation: s(args.graphRelation) || undefined, graphHops: Math.min(n(args.graphHops, 1, limits.maxGraphHops), limits.maxGraphHops), semanticGraphHops: Math.min(n(args.semanticGraphHops, 0, 2), 2), queryVector: Array.isArray(args.queryVector) ? args.queryVector.map(Number) : undefined, embeddingModel: s(args.embeddingModel) || undefined, embeddingModelVersion: s(args.embeddingModelVersion) || undefined, semanticLimit: Math.min(n(args.semanticLimit, limits.maxResults, limits.maxResults), limits.maxResults), overallLimit: Math.min(n(args.overallLimit, limits.maxResults, limits.maxResults), limits.maxResults), contextBudget: Math.min(n(args.contextBudget, 300, 5000), 5000), maxEdges: Math.min(n(args.maxEdges, 50, 250), 250), includeEvidence: args.includeEvidence === true, includeObservations: args.includeObservations === true, includeSources: args.includeSources === true, evidencePerIdentity: Math.min(n(args.evidencePerIdentity, 5, 20), 20), observationsPerIdentity: Math.min(n(args.observationsPerIdentity, 8, 50), 50), sourcesPerIdentity: Math.min(n(args.sourcesPerIdentity, 8, 25), 25) };
}

function createKnowledgeAgentTools(deps: Omit<KnowledgeAgentDependencies, "model" | "auditor">): AgentTool[] {
  const { canonical, retrieval, graph, vector, spatial } = deps;
  const pending = async (kind: KnowledgeProposal["kind"], payload: Record<string, unknown>, ctx: ToolContext) => {
    if (ctx.mode !== "curator") return { ok: false, error: "curation tools require curator mode" };
    if (ctx.proposalsUsed >= ctx.limits.maxProposals) return { ok: false, error: "proposal limit reached" };
    if (kind === "node" && (!s(payload.type) || !s(payload.label))) return { ok: false, error: "node type and label are required" };
    if (kind === "edge" && (!s(payload.fromId) || !s(payload.relation) || !s(payload.toId))) return { ok: false, error: "relation fromId, relation and toId are required" };
    if (kind === "evidence" && (!s(payload.targetId) || !s(payload.sourceId) || !s(payload.stance))) return { ok: false, error: "evidence targetId, sourceId and stance are required" };
    if (kind === "observation" && (!s(payload.targetId) || !s(payload.observationKind))) return { ok: false, error: "observation targetId and kind are required" };
    if (kind === "merge" && (!s(payload.fromId) || !s(payload.intoId) || payload.fromId === payload.intoId)) return { ok: false, error: "distinct merge fromId and intoId are required" };
    if (kind === "supersede" && (!s(payload.oldClaimId) || !s(payload.newClaimId) || payload.oldClaimId === payload.newClaimId)) return { ok: false, error: "distinct supersede oldClaimId and newClaimId are required" };
    const event = await canonical.createEvent({ sourceType: "manual", sourceRef: `knowledge-agent:${ctx.runId}` });
    const proposals = await canonical.addProposals(event.id, [{ kind, payload }]); ctx.proposalsUsed += proposals.length;
    return { ok: true, data: { eventId: event.id, proposals }, proposalIds: proposals.map((p) => p.id), canonicalIds: idsFrom(payload) };
  };
  const tools: AgentTool[] = [
    tool("knowledge.resolve_entity", "Resolve an explicit canonical ID/alias or return bounded same-label candidates and ambiguity.", "navigate", "none", async (a, c) => { const id = s(a.canonicalId); if (id) { const node = await canonical.getNode(id); return { ok: !!node, data: { node, ambiguous: false }, canonicalIds: node ? [node.id] : [], error: node ? undefined : "unknown canonical ID" }; } const label = s(a.label); if (!label) return { ok: false, error: "label or canonicalId is required" }; const type = s(a.type) || undefined; const resolved = await canonical.resolveCanonical({ label, type }); const matches = (await canonical.findNodes({ label, type, status: "accepted", limit: c.limits.maxResults })).filter((x) => normalizeLabel(x.label) === normalizeLabel(label)); return { ok: true, data: { node: resolved, candidates: resolved ? [resolved] : matches, ambiguous: !resolved && matches.length > 1 }, canonicalIds: (resolved ? [resolved] : matches).map((x) => x.id) }; }),
    tool("knowledge.retrieve", "Bounded canonical hybrid retrieval with exact, graph, semantic and provenance strategies.", "navigate", "none", async (a, c) => { const data = await retrieval.retrieve(request(a, c.limits)); return { ok: true, data, canonicalIds: data.items.map((x) => x.node.id), strategies: data.strategies }; }),
    tool("knowledge.semantic_search", "Run bounded pgvector discovery and canonical hydration; similarity never establishes identity.", "navigate", "none", async (a, c) => { if (!vector) return { ok: false, error: "vector repository unavailable" }; const data = await retrieval.retrieve(request({ ...a, overallLimit: a.limit }, c.limits)); return { ok: true, data, canonicalIds: data.items.map((x) => x.node.id), strategies: data.strategies }; }),
    tool("knowledge.graph_expand", "Expand accepted canonical topology in the graph engine.", "navigate", "none", async (a, c) => { if (!graph) return { ok: false, error: "graph repository unavailable" }; const root = s(a.canonicalId); const data = await graph.expand(root, { hops: Math.min(n(a.hops, 1, c.limits.maxGraphHops), c.limits.maxGraphHops), relation: s(a.relation) || undefined, workspaceId: a.workspaceId === null ? null : s(a.workspaceId) || undefined, status: "accepted", limit: c.limits.maxResults * 4 }); return { ok: true, data, canonicalIds: data.nodes.map((x) => x.id) }; }),
    tool("knowledge.find_path", "Find a bounded canonical path in the graph engine.", "navigate", "none", async (a, c) => { if (!graph) return { ok: false, error: "graph repository unavailable" }; const data = await graph.findPath({ fromCanonicalNodeId: s(a.fromId), toCanonicalNodeId: s(a.toId), maxHops: Math.min(n(a.maxHops, 4, c.limits.maxGraphHops), c.limits.maxGraphHops), workspaceId: a.workspaceId === null ? null : s(a.workspaceId) || undefined }); return { ok: true, data, canonicalIds: data?.nodes.map((x) => x.id) ?? [] }; }),
    tool("knowledge.get_node", "Get one canonical PostgreSQL identity by ID.", "navigate", "none", async (a) => { const data = await canonical.getNode(s(a.canonicalId)); return { ok: !!data, data, canonicalIds: data ? [data.id] : [], error: data ? undefined : "unknown canonical ID" }; }),
    tool("knowledge.get_claims", "Retrieve bounded accepted claims around canonical roots.", "navigate", "none", async (a, c) => { const data = await retrieval.retrieve(request({ ...a, graphRootIds: strings(a.rootIds), entityTypes: ["claim"] }, c.limits)); return { ok: true, data, canonicalIds: data.items.map((x) => x.node.id), strategies: data.strategies }; }),
    tool("knowledge.get_evidence", "Get qualified evidence for one canonical identity.", "navigate", "none", async (a, c) => { const id = s(a.canonicalId); const data = await canonical.listEvidence(id, Math.min(n(a.limit, c.limits.maxResults, c.limits.maxResults), c.limits.maxResults)); return { ok: true, data, canonicalIds: [id, ...data.map((x) => x.sourceNodeId)] }; }),
    tool("knowledge.get_observations", "Get occurrence/provenance history for one canonical identity.", "navigate", "none", async (a, c) => { const id = s(a.canonicalId); const data = await canonical.listObservations(id, Math.min(n(a.limit, c.limits.maxResults, c.limits.maxResults), c.limits.maxResults)); return { ok: true, data, canonicalIds: [id, ...data.flatMap((x) => x.sourceNodeId ? [x.sourceNodeId] : [])] }; }),
    tool("knowledge.get_sources", "Hydrate bounded canonical sources referenced by evidence and observations.", "navigate", "none", async (a, c) => { const id = s(a.canonicalId); const evidence = await canonical.listEvidence(id, c.limits.maxResults); const observations = await canonical.listObservations(id, c.limits.maxResults); const sourceIds = [...new Set([...evidence.map((x) => x.sourceNodeId), ...observations.flatMap((x) => x.sourceNodeId ? [x.sourceNodeId] : [])])].slice(0, c.limits.maxResults); const sources = (await Promise.all(sourceIds.map((x) => canonical.getNode(x)))).filter((x): x is KnowledgeNode => !!x); const eventIds = [...new Set([...evidence.flatMap((x) => x.sourceEventId ? [x.sourceEventId] : []), ...observations.flatMap((x) => x.sourceEventId ? [x.sourceEventId] : [])])].slice(0, c.limits.maxResults); const events = (await Promise.all(eventIds.map((x) => canonical.getEvent(x)))).filter(Boolean); return { ok: true, data: { sources, events }, canonicalIds: [id, ...sources.map((x) => x.id)] }; }),
    tool("knowledge.spatial_search", "Run bounded PostGIS search and hydrate canonical identities.", "navigate", "none", async (a, c) => { if (!spatial) return { ok: false, error: "spatial repository unavailable" }; const data = await retrieval.retrieve({ ...request(a, c.limits), spatial: { longitude: Number(a.longitude), latitude: Number(a.latitude), distanceMeters: Number(a.distanceMeters), limit: c.limits.maxResults } }); return { ok: true, data, canonicalIds: data.items.map((x) => x.node.id), strategies: data.strategies }; }),
    tool("knowledge.propose_entity", "Create a pending canonical identity proposal; never accepts it.", "curate", "proposals_only", (a, c) => pending("node", { type: s(a.type), label: s(a.label), description: s(a.description) || undefined, workspaceId: a.workspaceId === null ? null : s(a.workspaceId) || undefined, canonicalId: s(a.canonicalId) || undefined }, c)),
    tool("knowledge.propose_claim", "Create a pending claim proposal; never accepts it.", "curate", "proposals_only", (a, c) => pending("node", { type: "claim", label: s(a.label), description: s(a.description) || undefined, workspaceId: a.workspaceId === null ? null : s(a.workspaceId) || undefined, canonicalId: s(a.canonicalId) || undefined }, c)),
    tool("knowledge.propose_relation", "Create a pending typed relation proposal between canonical IDs.", "curate", "proposals_only", (a, c) => pending("edge", { fromId: s(a.fromId), relation: s(a.relation), toId: s(a.toId), confidence: typeof a.confidence === "number" ? a.confidence : undefined }, c)),
    tool("knowledge.propose_evidence", "Create pending qualified evidence for any canonical identity.", "curate", "proposals_only", (a, c) => pending("evidence", { targetId: s(a.targetId), sourceId: s(a.sourceId), stance: s(a.stance), excerpt: s(a.excerpt) || undefined, confidence: typeof a.confidence === "number" ? a.confidence : undefined }, c)),
    tool("knowledge.propose_observation", "Create a pending occurrence/provenance binding, distinct from evidence.", "curate", "proposals_only", (a, c) => pending("observation", { targetId: s(a.targetId), sourceId: s(a.sourceId) || undefined, observationKind: s(a.kind), observationMetadata: a.metadata && typeof a.metadata === "object" ? a.metadata : undefined }, c)),
    tool("knowledge.propose_merge", "Propose canonical identity consolidation for separate approval; does not merge.", "curate", "proposals_only", (a, c) => pending("merge", { fromId: s(a.fromId), intoId: s(a.intoId), rationale: s(a.rationale) || undefined }, c)),
    tool("knowledge.propose_supersede", "Propose claim supersession for separate approval; does not change claim status.", "curate", "proposals_only", (a, c) => pending("supersede", { oldClaimId: s(a.oldClaimId), newClaimId: s(a.newClaimId), markOldDisputed: a.markOldDisputed !== false, rationale: s(a.rationale) || undefined }, c)),
    tool("knowledge.inspect_duplicates", "Return bounded possible duplicate candidates and opposing signals; never merges.", "inspect", "none", async (a, c) => { const label = s(a.label); const type = s(a.type) || undefined; const candidates = (await canonical.findNodes({ label, type, status: "accepted", limit: c.limits.maxResults })).filter((x) => normalizeLabel(x.label) === normalizeLabel(label)); const aliases = await canonical.listAliases(); const data = candidates.map((x) => ({ canonicalId: x.id, label: x.label, type: x.type, workspaceId: x.workspaceId, supportingSignals: ["normalized_label"], distinctnessSignals: candidates.filter((y) => y.id !== x.id && y.type !== x.type).length ? ["type_difference"] : [], ambiguity: candidates.length > 1 ? "unresolved" : "low" , aliases: aliases.filter((v) => v.canonicalNodeId === x.id).map((v) => v.aliasLabel) })); return { ok: true, data: { candidates: data, autoMerged: false, semanticSimilarityEstablishesIdentity: false }, canonicalIds: candidates.map((x) => x.id) }; }),
    tool("knowledge.inspect_conflicts", "Inspect explicit contradictions and supersession topology without truth arbitration.", "inspect", "none", async (a, c) => { const nodeId = s(a.canonicalId) || undefined; const contradictions = await canonical.findContradictions({ nodeId, limit: c.limits.maxResults }); const topology = nodeId ? await canonical.getNeighborhood(nodeId, { hops: 1, status: "accepted" }) : { nodes: [], edges: [] }; const supersessions = topology.edges.filter((x) => x.relation === "supersedes"); return { ok: true, data: { contradictions, supersessions, arbitrated: false }, canonicalIds: [...new Set([...contradictions.flatMap((x) => [x.from.id, x.to.id]), ...supersessions.flatMap((x) => [x.fromNodeId, x.toNodeId])])] }; }),
    tool("knowledge.inspect_structure", "Conservatively inspect supplied canonical IDs for invalid provenance references or suspicious isolation; zero degree alone is not an error.", "inspect", "none", async (a, c) => { const ids = strings(a.canonicalIds).slice(0, c.limits.maxResults); const issues: unknown[] = []; for (const id of ids) { const node = await canonical.getNode(id); if (!node) { issues.push({ canonicalId: id, issue: "missing_identity" }); continue; } const neighborhood = await canonical.getNeighborhood(id, { hops: 1, status: "accepted" }); const evidence = await canonical.listEvidence(id, c.limits.maxResults); const observations = await canonical.listObservations(id, c.limits.maxResults); for (const item of evidence) if (!(await canonical.getNode(item.sourceNodeId))) issues.push({ canonicalId: id, evidenceId: item.id, issue: "missing_evidence_source" }); for (const item of observations) if (item.sourceNodeId && !(await canonical.getNode(item.sourceNodeId))) issues.push({ canonicalId: id, observationId: item.id, issue: "missing_observation_source" }); if (!neighborhood.edges.length) issues.push({ canonicalId: id, issue: "isolated_review_candidate", severity: "informational", note: "zero degree is not inherently invalid" }); } return { ok: true, data: { inspected: ids.length, issues: issues.slice(0, c.limits.maxResults), conservative: true }, canonicalIds: ids }; }),
  ];
  return tools;
}

export class KnowledgeAgentService {
  private readonly tools: AgentTool[];
  constructor(private readonly deps: KnowledgeAgentDependencies) { this.tools = createKnowledgeAgentTools(deps); }
  listTools(mode: KnowledgeAgentMode): KnowledgeAgentToolSchema[] { return this.tools.filter((x) => mode === "curator" || x.schema.capability !== "curate").map((x) => x.schema); }
  async run(input: KnowledgeAgentRunRequest): Promise<KnowledgeAgentRunResult> {
    const runId = randomUUID(); const mode = input.mode ?? "navigator"; const limits: Required<KnowledgeAgentLimits> = { maxToolCalls: Math.min(n(input.limits?.maxToolCalls, 8, 24), 24), maxContextChars: Math.min(n(input.limits?.maxContextChars, 40_000, 200_000), 200_000), maxGraphHops: Math.min(n(input.limits?.maxGraphHops, 3, 6), 6), maxResults: Math.min(n(input.limits?.maxResults, 20, 100), 100), maxProposals: Math.min(n(input.limits?.maxProposals, 8, 25), 25) };
    const schemas = this.listTools(mode); const allowed = new Map(this.tools.filter((x) => schemas.some((v) => v.name === x.schema.name)).map((x) => [x.schema.name, x])); const steps: KnowledgeAgentRunResult["steps"] = []; const proposalIds = new Set<string>(); const canonicalIds = new Set<string>(); const degraded = new Set<string>(); const context: ToolContext = { runId, mode, limits, proposalsUsed: 0 }; let contextChars = 0; let answer = ""; let outcome: KnowledgeAgentOutcome = "insufficient"; let hitToolLimit = false;
    this.deps.auditor?.emit({ runId, mode, phase: "start", counts: { maxToolCalls: limits.maxToolCalls, maxResults: limits.maxResults, maxProposals: limits.maxProposals } });
    for (let index = 0; index <= limits.maxToolCalls; index++) {
      const decision = await this.deps.model.next({ runId, mode, goal: input.goal, policy: mode === "navigator" ? NAVIGATOR_POLICY : CURATOR_POLICY, tools: schemas, steps: steps.map((x) => ({ tool: x.tool, result: x.result })), remainingToolCalls: Math.max(0, limits.maxToolCalls - steps.length), remainingProposals: Math.max(0, limits.maxProposals - context.proposalsUsed) });
      if (decision.kind === "final") { answer = decision.answer; outcome = decision.outcome ?? (proposalIds.size ? "proposed" : "answered"); break; }
      if (steps.length >= limits.maxToolCalls) { hitToolLimit = true; answer = "Knowledge Agent stopped at the configured tool-call limit."; outcome = "bounded"; break; }
      const selected = allowed.get(decision.tool); let result: KnowledgeAgentToolResult;
      if (!selected) result = { ok: false, error: `tool is unavailable in ${mode} mode` };
      else try { result = await selected.execute(decision.args, context); } catch (error) { result = { ok: false, error: error instanceof Error ? error.message : String(error) }; }
      const serialized = JSON.stringify(result); if (contextChars + serialized.length > limits.maxContextChars) { result = { ok: false, error: "agent retrieval context limit reached", canonicalIds: result.canonicalIds?.slice(0, limits.maxResults), proposalIds: result.proposalIds }; outcome = "bounded"; } else contextChars += serialized.length;
      result.canonicalIds?.forEach((id) => canonicalIds.add(id)); result.proposalIds?.forEach((id) => proposalIds.add(id)); degradedFrom(result.strategies).forEach((name) => degraded.add(name)); steps.push({ tool: decision.tool, args: decision.args, result });
      this.deps.auditor?.emit({ runId, mode, phase: "tool", tool: decision.tool, ok: result.ok, canonicalIds: result.canonicalIds, proposalIds: result.proposalIds, strategies: result.strategies, degraded: degradedFrom(result.strategies), counts: { contextChars, toolCalls: steps.length, proposals: proposalIds.size } });
    }
    if (!answer) { hitToolLimit = true; answer = "Knowledge Agent stopped at a configured execution bound."; outcome = "bounded"; }
    this.deps.auditor?.emit({ runId, mode, phase: "finish", outcome, canonicalIds: [...canonicalIds], proposalIds: [...proposalIds], degraded: [...degraded], counts: { contextChars, toolCalls: steps.length, proposals: proposalIds.size } });
    return { runId, mode, answer, outcome, steps, proposalIds: [...proposalIds], canonicalIds: [...canonicalIds], degradedDependencies: [...degraded], hitToolLimit };
  }
}
export function createKnowledgeAgent(dependencies: KnowledgeAgentDependencies): KnowledgeAgentService { return new KnowledgeAgentService(dependencies); }
export { NAVIGATOR_POLICY as KNOWLEDGE_NAVIGATOR_POLICY, CURATOR_POLICY as KNOWLEDGE_CURATOR_POLICY };
